### ISSUE TITLE
cache & out folders generated everywhere

### ISSUE THREAD

**Issue by Austinhs** [panukettu/vscode-solidity#1]
Seems like no matter what repo I open this extension creates a cache & out folder. Thinking we should check if a .sol file exists somewhere in the project before creating these.

**Comment by panukettu** [comment]
Might be the "monoRepoSupport". That now defaults to false as I haven't had time to really see if it works.

Anyways you can now set the directory for compilation output with `solidity.outDir`. If you are using the forge test execution feature it will ofc build your stuff and the folders defined in your repositorys `foundry.toml`.
