### ISSUE TITLE
Request: Set 'foundry.toml' root to a folder deeper in workspace

### ISSUE THREAD

**Issue by Cygnusfear** [panukettu/vscode-solidity#4]
Just stumbled upon this VSCode extension- 🤩✨

At the moment I'm working on a project where the Contracts are inside the monorepo at
`/packages/contracts/`
and the plugin is searching at
`/`

That would be a great setting to have.

Looking forward to using this more 🙏🍀
Thank you for your efforts.

**Comment by panukettu** [comment]
> Just stumbled upon this VSCode extension- 🤩✨
> 
> At the moment I'm working on a project where the Contracts are inside the monorepo at `/packages/contracts/` and the plugin is searching at `/`
> 
> That would be a great setting to have.
> 
> Looking forward to using this more 🙏🍀 Thank you for your efforts.

Thanks for the feedback!

I made a new release (0.9.11) with improved root path support.

You can try to set either one of following:

1. `solidity.project.root` directly set (inner)root folder so in this case "packages/contracts"
2. `solidity.project.monorepo` if set to true, tries to find a foundry.toml and sets that directory as root

**Comment by panukettu** [comment]
lmk if it does not work for you
